version: "3.9"

services:
  iac:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      args:
        - REMOTE_USER=${IAC_REMOTE_USER}
        - REMOTE_WORKSPACES=${IAC_REMOTE_WORKSPACES}
        - REMOTE_HOME=${IAC_REMOTE_HOME}
    container_name: ${IAC_CONTAINER_NAME}
    working_dir: ${IAC_REMOTE_WORKSPACES}
    user: ${IAC_REMOTE_USER}
    tty: true
    dns:
      - 8.8.8.8
    volumes:
      - type: bind
        source: .
        target: ${PROJECT_ROOT}
      - type: volume
        source: iac_bash_history
        target: /commandhistory
      - type: volume
        source: iac_vscode_extensions
        target: ${IAC_REMOTE_HOME}/.vscode-server/extensions
      - type: volume
        source: iac_node_modules
        target: ${IAC_REMOTE_WORKSPACES}/node_modules
      - type: volume
        source: iac_gcloud
        target: ${IAC_REMOTE_HOME}/.config/gloud

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

volumes:
  iac_bash_history:
    name: ${IAC_BASH_HISTORY_VOLUME_NAME}
  iac_vscode_extensions:
    name: ${IAC_VSCODE_EXTENSIONS_VOLUME_NAME}
  iac_node_modules:
    name: ${IAC_NODE_MODULES_VOLUME_NAME}
  iac_gcloud:
    name: ${IAC_GCLOUD_VOLUME_NAME}
